/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_card_CardThread */

#ifndef _Included_com_example_card_CardThread
#define _Included_com_example_card_CardThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_card_CardThread_MIN_PRIORITY
#define com_example_card_CardThread_MIN_PRIORITY 1L
#undef com_example_card_CardThread_NORM_PRIORITY
#define com_example_card_CardThread_NORM_PRIORITY 5L
#undef com_example_card_CardThread_MAX_PRIORITY
#define com_example_card_CardThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
