/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_card_GameActivity_EventHandler */

#ifndef _Included_com_example_card_GameActivity_EventHandler
#define _Included_com_example_card_GameActivity_EventHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
